parameters:
    dacorp.menu_builder.class:  Dacorp\ExtraBundle\Menu\MenuBuilder

services:
    dacorp.menu_builder:
        class: %dacorp.menu_builder.class%
        arguments: ["@knp_menu.factory", "@service_container"]
